### ISSUE TITLE
ReadAttachments downloads the files instead of opening them in a new tab

### ISSUE THREAD

**Issue by yashmeet29** [cap-java/cds-feature-attachments#227] opened 2024-10-10 07:25 UTC
I am part of the team that is developing the [SDM plugin](https://github.com/cap-java/sdm). I have implemented Read Attachments feature for SDM Java plugin. In my readAttachment implementation after i fetch the content of attachment from SDM, I set the content in context as below
`context.getData().setContent(documentStream);`

With this implementation, upon reading the attachment, all the attachments are getting downloaded. Ideally it should open the file in new browser tab for the file types that are supported in browser. In NodeJs SDM plugin file types like .pdf, .txt opens in new browser tabs and .docxs & .xlsx gets downloaded as these file types are not supported in browser tabs.

**Comment by mofterdinger** [comment] 2024-10-10 08:30
Hi, using the cds-feature-attachment in the bookshop, the covers (attachments) are opened in a new Browser tab, if I click on the link:

<img width="406" alt="image" src="https://github.com/user-attachments/assets/84f97949-b34e-41c1-b55a-b5ade1539b85">

I don't see an error with the cds-feature-attachment here.

Thanks,
Markus

**Comment by adamandre79** [comment] 2024-10-11 07:56
Hi @yashmeet29 ,

I do not implement some logic for this in the attachments plugin and I think it is a browser setting. Does it work for you with the attachments plugin?

Regards
André

**Comment by yashmeet29** [comment] 2024-10-14 07:23
Hi @adamandre79, it cannot be a browser setting, because for node-js sdm plugin, attachments are opening in new browser tab.

**Comment by adamandre79** [comment] 2024-10-14 07:53
Hello @yashmeet29 ,

does it work with the Java attachment plugin?

Regards
André

**Comment by mofterdinger** [comment] 2024-10-14 09:50
Hi, as discussed in a meeting, this issue is caused by the Fiori UI. It doesn't support eTag handling on streams (content upload) at the moment or it's a bug. A [SNOW issue](https://itsm.services.sap/now/cwf/agent/record/x_sapda_devinc_development_incident/11fd8147c30d5610e470069dc0013110) is already opened for it. As workaround just disable eTag support on the filed modifiedBy as shown here: https://github.com/SAP-samples/cloud-cap-samples-java/pull/377/files#diff-d92b8eb29957a03ad9d23b01feff79da293e30183d0b8eac5d893d95632e30dfR39

Therefore I close this issue.

Thanks,
Markus

**Closed by mofterdinger** 2024-10-14 09:50 UTC

**Comment by mofterdinger** [comment] 2024-10-17 15:57
@yashmeet29 Hi, finally I found the root cause for the behavior that attachments are downloaded instead of opened in a new tab. It is a gap in the OData V4 layer of cds-services and it's not related to cds-feature-attachments.
The gap will be closed with this PR: https://github.wdf.sap.corp/cds-java/cds-services/pull/4459

Thanks,
Markus

**Comment by yashmeet29** [comment] 2024-10-18 04:36
@mofterdinger thanks for updating, i will check once the PR is merged.

Regards,
Yashmeet
